### TUGAS DATA MINING ASSOCIATION LEARNING
Jonathan Joyo Wibowo

5054251026

Rekayasa Kecerdasan Artifisial

### SETUP

In [69]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
from google.colab import drive

from mlxtend.frequent_patterns import apriori, association_rules, fpgrowth
SEED = 67  # six seven

In [70]:
warnings.filterwarnings('ignore', category=DeprecationWarning)

In [71]:
uploaded = drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [72]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_columns', None)

### LOAD DATA

In [73]:
df_data = pd.read_excel("/content/drive/MyDrive/dataset/online_retail/Online_Retail.xlsx")

In [74]:
df_data_raw = df_data.copy()

### EDA

In [75]:
df_data.head()

  InvoiceNo StockCode                          Description  Quantity         InvoiceDate  UnitPrice  CustomerID         Country
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6 2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1    536365     71053                  WHITE METAL LANTERN         6 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8 2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6 2010-12-01 08:26:00       3.39     17850.0  United Kingdom

In [76]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [77]:
df_data.nunique()

InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64

In [78]:
df_data.shape

(541909, 8)

In [79]:
df_data["Quantity"].describe()

count    541909.000000
mean          9.552250
std         218.081158
min      -80995.000000
25%           1.000000
50%           3.000000
75%          10.000000
max       80995.000000
Name: Quantity, dtype: float64

In [80]:
df_data[df_data["Quantity"] < 1].count()

InvoiceNo      10624
StockCode      10624
Description     9762
Quantity       10624
InvoiceDate    10624
UnitPrice      10624
CustomerID      8905
Country        10624
dtype: int64

### Preprocessing

In [81]:
df_data = df_data_raw.copy()

In [82]:
# Hapus duplikat
df_data = df_data.drop_duplicates()

# Hapus duplikat pada subset InvoiceNo, StockCode
# Karena kita tidak peduli seberapa banyak suatu barang ada pada suatu basket/transaksi
# Kita hanya peduli apakah suatu barang ADA atau TIDAK

df_data = df_data.drop_duplicates(subset=["InvoiceNo", "StockCode"])

In [83]:
# Hapus data yang quantity <= 0
df_data = df_data[df_data["Quantity"] > 0]
df_data = df_data.reset_index(drop=True)

# Hapus juga yang quantity >= 80000 (tidak normal)
df_data = df_data[df_data["Quantity"] < 80000]
df_data = df_data.reset_index(drop=True)

In [84]:
df_data.shape

(520749, 8)

In [85]:
# Hapus transaksi yang di-cancel
cancelled_mask = df_data["InvoiceNo"].str.contains(r"^C", case=False, na=False)
df_data = df_data[~cancelled_mask]

In [86]:
df_data.shape

(520749, 8)

In [87]:
# drop kolom yang tidak perlu
# kita cuma pake InvoiceNo sama StockCode

# InvoiceNo buat ngelompokkin barang jadi basket-basket belanja

# StockCode buat mengidentifikasi barangnya
# sebenernya bisa pake Description. StockCode dan Description itu multikolinear,
# tapi karena Deskripsi lebih rawan typo, saya pake StockCode

df_data = df_data.drop(columns=["Description", "Quantity", "InvoiceDate",	"UnitPrice", "CustomerID", "Country"], axis=1)

In [88]:
df_data.head()

  InvoiceNo StockCode
0    536365    85123A
1    536365     71053
2    536365    84406B
3    536365    84029G
4    536365    84029E

In [89]:
# Kelompokkan data ke dalam basket
basket = pd.crosstab(df_data["InvoiceNo"], df_data["StockCode"])

In [90]:
basket.head()

StockCode  10002  10080  10120  10125  10133  10135  11001  15030  15034  15036  15039  16008  16010  16011  16012  16014  16015  16016  16033  16043  16045  16046  16048  16049  16052  16054  16216  16218  16219  16225  16235  16236  16237  16238  16254  16259  17001  17003  17021  17038  17096  17174  18007  20615  20616  20617  20618  20619  20622  20652  20653  20654  20655  20657  20658  20659  20661  20662  20663  20664  20665  20666  20667  20668  20669  20670  20671  20674  20675  20676  20677  20678  20679  20681  20682  20684  20685  20686  20694  20695  20696  20697  20698  20699  20700  20701  20702  20703  20704  20705  20707  20711  20712  20713  20716  20717  20718  20719  20723  20724  20725  20726  20727  20728  20731  20733  20734  20735  20748  20749  20750  20751  20752  20754  20755  20756  20757  20758  20759  20760  20761  20762  20763  20764  20765  20766  20767  20768  20769  20770  20771  20772  20773  20774  20775  20777  20778  20780  20781  20782  20785  \
InvoiceNo
536365         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0
536366         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0
536367         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0
536368         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0
536369         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0

StockCode  20793  20794  20795  20796  20798  20801  20802  20803  20816  20818  20819  20820  20821  20823  20826  20827  20828  20829  20830  20831  20832  20835  20836  20837  20838  20839  20840  20845  20846  20847  20848  20849  20851  20854  20856  20857  20860  20861  20866  20867  20868  20869  20871  20878  20886  20892  20893  20894  20897  20898  20901  20902  20903  20906  20910  20914  20931  20932  20933  20934  20935  20936  20941  20950  20954  20956  20960  20961  20963  20964  20966  20967  20969  20970  20971  20972  20973  20974  20975  20977  20978  20979  20980  20981  20982  20983  20984  20985  20986  20992  20996  20997  20998  21000  21001  21002  21003  21009  21011  21012  21014  21015  21018  21025  21026  21027  21028  21030  21031  21032  21033  21034  21035  21038  21039  21040  21041  21042  21043  21051  21054  21055  21056  21058  21059  21060  21061  21062  21063  21064  21065  21066  21067  21068  21069  21070  21071  21078  21080  21082  21084  \
InvoiceNo
536365         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0
536366         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0
536367         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0
536368         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0
536369         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0

StockCode  21086  21087  21088  21089  21090  21094  21095  21096  21098  21100  21106  21107  21108  21109  21110  21111  21112  21114  21115  21116  21117  21120  21121  21122  21123  21124  21125  21126  21128  21129  21131  21132  21134  21135  21136  21137  21143  21144  21145  21147  21154  21155  21156  21157  21158  21159  21160  21161  21162  21163  21164  21165  21166  21167  21169  21171  21172  21174  21175  21179  21181  21186  21187  21188  21189  21190  21191  21192  21194  21195  21196  21197  21198  21199  21200  21201  21202  21204  21205  21206  21207  21208  21209  21210  21211  21212  21213  21215  21216  21217  21218  21219  21220  21221  21222  21224  21226  21228  21231  21232  21238  21239  21240  21242  21243  21244  21245  21246  21248  21249  21250  21251  21253  21257  21258  21259  21260  21261  21262  21263  21264  21265  21268  21269  21270  21272  21275  21277  21278  21279  21280  21281  21284  21285  21286  21287  21288  21289  21291  21292  21293  \
InvoiceNo
536365         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0
536366         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0
536367         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0
536368         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0
536369         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0

StockCode  21294  21306  21307  21310  21311  21313  21314  21316  21317  21318  21319  21320  21324  21326  21327  21328  21329  21331  21332  21333  21336  21340  21344  21348  21349  21351  21352  21354  21355  21356  21357  21358  21359  21360  21361  21363  21364  21365  21366  21367  21368  21369  21370  21371  21372  21373  21374  21375  21376  21377  21378  21379  21380  21381  21382  21383  21385  21386  21389  21390  21391  21392  21393  21394  21395  21397  21398  21399  21400  21401  21402  21403  21407  21408  21410  21411  21413  21414  21415  21416  21417  21418  21420  21421  21422  21424  21425  21426  21427  21428  21429  21430  21439  21441  21442  21445  21446  21447  21448  21452  21454  21455  21456  21457  21458  21459  21460  21461  21462  21463  21464  21465  21466  21467  21468  21469  21470  21471  21472  21473  21476  21479  21481  21484  21485  21486  21488  21491  21494  21495  21497  21498  21499  21500  21503  21504  21506  21507  21508  21509  21518  \
InvoiceNo
536365         0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0

In [91]:
basket.describe()

StockCode         10002         10080         10120         10125         10133         10135         11001         15030         15034         15036         15039         16008         16010         16011         16012         16014         16015         16016         16033         16043         16045         16046         16048         16049         16052         16054         16216         16218         16219         16225         16235         16236         16237         16238         16254         16259         17001         17003         17021         17038         17096         17174         18007         20615         20616         20617         20618         20619         20622         20652         20653         20654         20655         20657         20658         20659         20661         20662         20663         20664         20665         20666         20667         20668         20669         20670         20671        20674         20675         20676  \
count      20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.00000  20727.000000  20727.000000
mean           0.003474      0.001158      0.001399      0.004390      0.009456      0.008443      0.005452      0.000627      0.006658      0.024992      0.006996      0.003377      0.000145      0.002219      0.001689      0.002605      0.001206      0.003136      0.000241      0.000096      0.003281      0.000724      0.003232      0.000289      0.000627      0.001592      0.002171      0.003088      0.004825      0.004921      0.008105      0.006561      0.013991      0.006465      0.000820      0.001496      0.000048      0.011531      0.002268      0.001640      0.001158      0.000145      0.001447      0.004680      0.003425      0.002075      0.003667      0.004776      0.002461      0.003860      0.001592      0.002364      0.004776      0.001592      0.005066      0.002991      0.001592      0.000965      0.000965      0.000917      0.007575      0.000820      0.000772      0.010373      0.004632      0.000531      0.000096      0.00989      0.015535      0.021614
std            0.058837      0.034009      0.037380      0.066116      0.096785      0.091500      0.073637      0.025037      0.081326      0.156103      0.083349      0.058017      0.012030      0.047059      0.041059      0.050977      0.034710      0.055914      0.015530      0.009823      0.057185      0.026892      0.056764      0.017012      0.025037      0.039871      0.046545      0.055483      0.069293      0.069980      0.089666      0.080739      0.117458      0.080147      0.028628      0.038645      0.006946      0.106763      0.047566      0.040469      0.034009      0.012030      0.038018      0.068251      0.058429      0.045501      0.060444      0.068948      0.049544      0.062008      0.039871      0.048565      0.068948      0.039871      0.070996      0.054612      0.039871      0.031049      0.031049      0.030264      0.086704      0.028628      0.027774      0.101320      0.067900      0.023032      0.009823      0.09896      0.123672      0.145424
min            0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000      0.000000      0.000000
25%            0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000      0.000000      0.000000
50%            0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000      0.000000      0.000000
75%            0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000      0.000000      0.000000
max            1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.00000      1.000000      1.000000

StockCode         20677         20678         20679         20681         20682         20684         20685         20686         20694         20695         20696         20697         20698         20699         20700         20701         20702         20703         20704         20705         20707         20711         20712         20713         20716         20717         20718         20719         20723         20724         20725         20726         20727         20728         20731        20733         20734         20735         20748         20749         20750         20751         20752         20754         20755         20756         20757         20758         20759         20760         20761         20762         20763         20764         20765        20766         20767         20768         20769         20770         20771         20772         20773         20774         20775         20777         20778         20780         20781         20782  \
count      20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.00000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.00000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000
mean           0.016066      0.000048      0.015728      0.002219      0.011579      0.001737      0.033628      0.003715      0.000772      0.000193      0.001447      0.000531      0.000386      0.001978      0.002605      0.000868      0.002075      0.000048      0.002123      0.001351      0.007189      0.025233      0.041637      0.032084      0.003570      0.019877      0.027742      0.040286      0.034834      0.049887      0.075505      0.049115      0.061417      0.055483      0.000868      0.00989      0.001303      0.005452      0.001737      0.018478      0.018575      0.009553      0.007140      0.014715      0.002991      0.001061      0.001592      0.002026      0.000965      0.001061      0.003040      0.002702      0.001303      0.003667      0.002847      0.00275      0.003811      0.002654      0.001640      0.003474      0.001930      0.003136      0.001110      0.002171      0.003040      0.003860      0.000434      0.001351      0.001206      0.001303
std            0.125732      0.006946      0.124425      0.047059      0.106984      0.041641      0.180273      0.060839      0.027774      0.013891      0.038018      0.023032      0.019643      0.044433      0.050977      0.029457      0.045501      0.006946      0.046026      0.036731      0.084483      0.156835      0.199762      0.176227      0.059646      0.139583      0.164235      0.196633      0.183363      0.217716      0.264211      0.216113      0.240100      0.228926      0.029457      0.09896      0.036070      0.073637      0.041641      0.134676      0.135021      0.097273      0.084201      0.120413      0.054612      0.032563      0.039871      0.044970      0.031049      0.032563      0.055049      0.051910      0.036070      0.060444      0.053278      0.05237      0.061621      0.051445      0.040469      0.058837      0.043889      0.055914      0.033294      0.046545      0.055049      0.062008      0.020834      0.036731      0.034710      0.036070
min            0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000
25%            0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000
50%            0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000
75%            0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.00000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000
max            1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.00000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.00000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000      1.000000

StockCode         20785         20793         20794         20795         20796         20798         20801         20802         20803         20816         20818         20819         20820         20821         20823         20826         20827         20828         20829         20830         20831         20832         20835         20836         20837        20838         20839         20840         20845         20846         20847         20848         20849         20851         20854         20856         20857         20860         20861         20866         20867         20868         20869         20871         20878         20886         20892         20893         20894         20897         20898         20901         20902         20903         20906         20910         20914         20931         20932         20933         20934         20935         20936         20941         20950         20954         20956         20960         20961         20963  \
count      20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.00000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000  20727.000000

In [92]:
# Opsional, buat dataframe yang isinya StockCode & Description
# nanti bisa dipake buat lookup kira-kira StockCode yang muncul
# di rule association itu produk apa

df_lookup = df_data_raw.copy()
df_lookup = df_lookup[["StockCode", "Description"]]

# drop duplikat
df_lookup = df_lookup.drop_duplicates()

# convert StockCode ke string
df_lookup["StockCode"] = df_lookup["StockCode"].astype(str)

### MODELING

In [93]:
freq_itemsets_apriori = apriori(basket, min_support=0.01, use_colnames=True, low_memory=True)

rules_apriori = association_rules(freq_itemsets_apriori,
                          metric="confidence",
                          min_threshold=0.5)

In [94]:
freq_itemsets_fpgrowth = fpgrowth(basket, min_support=0.01, use_colnames=True)

rules_fpgrowth = association_rules(freq_itemsets_fpgrowth,
                          metric="confidence",
                          min_threshold=0.5)

In [95]:
rules_fpgrowth.sort_values(by="lift", ascending=False).head(3)

    antecedents consequents  antecedent support  consequent support   support  confidence       lift  representativity  leverage  conviction  zhangs_metric   jaccard  certainty  kulczynski
373     (22916)     (22917)            0.011434            0.011579  0.010662    0.932489  80.532120               1.0  0.010530   14.640985       0.999006  0.863281   0.931699    0.926661
374     (22917)     (22916)            0.011579            0.011434  0.010662    0.920833  80.532120               1.0  0.010530   12.487145       0.999152  0.863281   0.919918    0.926661
375     (22916)     (22918)            0.011434            0.011483  0.010276    0.898734  78.269173               1.0  0.010145    9.761609       0.998642  0.812977   0.897558    0.896846

In [96]:
rules_fpgrowth.sort_values(by="lift", ascending=False).head(3)

    antecedents consequents  antecedent support  consequent support   support  confidence       lift  representativity  leverage  conviction  zhangs_metric   jaccard  certainty  kulczynski
373     (22916)     (22917)            0.011434            0.011579  0.010662    0.932489  80.532120               1.0  0.010530   14.640985       0.999006  0.863281   0.931699    0.926661
374     (22917)     (22916)            0.011579            0.011434  0.010662    0.920833  80.532120               1.0  0.010530   12.487145       0.999152  0.863281   0.919918    0.926661
375     (22916)     (22918)            0.011434            0.011483  0.010276    0.898734  78.269173               1.0  0.010145    9.761609       0.998642  0.812977   0.897558    0.896846

In [97]:
stock_codes = ["22916", "22917", "22918"]

df_lookup[df_lookup["StockCode"].isin(stock_codes)]

    StockCode           Description
974     22917  HERB MARKER ROSEMARY
977     22918   HERB MARKER PARSLEY
978     22916     HERB MARKER THYME

### INTERPRETASI

Ada 3 Aturan dengan skor lift tertinggi, yaitu:
1. Herb Marker Thyme (22916) -> Herb Marker Rosemary (22917)
2. Herb Marker Rosemary (22917) -> Herb Marker Thyme (22916)
3. Herb Marker Thyme (22916) -> Herb Marker Parsley (22918)

Aturan Pertama itu Confidencenya 93.24%, berarti jika Herb Marker Thyme (22916) dibeli, maka kemungkinan buat Herb Marker Rosemary (22917) dibeli itu 93.24%

Liftnya 80.53, berarti jika Herb Marker Thyme (22916) dibeli, maka kemungkinan buat Herb Marker Rosemary (22917) dibeli itu naik 80.53 kali lipat, yang awalnya 1.15% (Antecedent Consequent), naik jadi 93.24%

Aturan Kedua itu Confidencenya 92.08%, berarti jika Herb Marker Rosemary (22917) dibeli, maka kemungkinan buat Herb Marker Thyme (22916) dibeli itu 92.08%

Liftnya 80.53, berarti jika Herb Marker Rosemary (22917) dibeli, maka kemungkinan buat Herb Marker Thyme (22916) dibeli itu naik 80.53 kali lipat, yang awalnya 1.14% (Antecedent Consequent), naik jadi 92.08%

Aturan Pertama itu Confidencenya 89.87%, berarti jika Herb Marker Thyme (22916) dibeli, maka kemungkinan buat Herb Marker Parsley (22918) dibeli itu 89.87%

Liftnya 78.26, berarti jika Herb Marker Thyme (22916) dibeli, maka kemungkinan buat Herb Marker Parsley (22918) dibeli itu naik 78.26 kali lipat, yang awalnya 1.14% (Antecedent Consequent), naik jadi 89.87%